package com.example.famlistapp.data.model

data class User(
    val id: String, // Generated by Supabase
    val nickname: String,
    val avatarUrl: String, // Placeholder, could be a URL or local resource ID
    val isOnline: Boolean = false,
    val lastSeenTimestamp: Long = 0L // Unix timestamp
)
